---
# Run using e.g.  ansible-playbook -v --ask-become -i "$(hostname --short)," local.yml
- hosts: all
  connection: local
  become: false
  # vars:
  #   target_user: "{{ ansible_env.USER }}"
  tasks:
    - include_tasks: tasks/wsl.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/vcc.yml
    - include_tasks: tasks/python.yml
    - include_tasks: tasks/font.yml
    - include_tasks: tasks/emacs.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/direnv.yml
    # - include_tasks: tasks/packages.yml

  handlers:
    - import_tasks: handlers/main.yml
