---
# Run using e.g.  ansible-playbook -v --ask-become -i "$(hostname --short)," local.yml
- hosts: all
  connection: local
  become: false
  # vars:
  #   target_user: "{{ ansible_env.USER }}"
  tasks:
    - name: Check if we are running on WSL
      ansible.builtin.shell: systemd-detect-virt
      register: systemd_detect_virt
      changed_when: false
      ignore_errors: true

    - name: Set fact for wsl
      ansible.builtin.set_fact:
        is_wsl: "{{ systemd_detect_virt.stdout == 'wsl' }}"

    - name: Show value
      debug:
        var: is_wsl

    - include_tasks: tasks/wsl.yml
      when: is_wsl

    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/vcc.yml
    - include_tasks: tasks/python.yml

    - include_tasks: tasks/font.yml
      when: not is_wsl

    - include_tasks: tasks/emacs.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/direnv.yml
    - include_tasks: tasks/wezterm.yml
    # - include_tasks: tasks/packages.yml

  handlers:
    - import_tasks: handlers/main.yml
