---
- hosts: all
  connection: local
  become: false

  tasks:
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/emacs.yml
    # - include_tasks: tasks/packages.yml
    # - include_tasks: tasks/zsh.yml
