- name: Install required packages for handling dotfiles
  become: true
  ansible.builtin.apt:
    name:
      - git
      - stow
    cache_valid_time: 3600
    state: present
    install_recommends: no

- name: Dump info
  debug:
    var: ansible_env.HOME

- name: Checkout dotfile repo from github
  ansible.builtin.git:
    repo: git@github.com:Cecron/dotfiles.git
    dest: "{{ ansible_env.HOME }}/dotfiles"

# This uses the locally installed module stow.
# https://github.com/caian-org/ansible-stow
- name: Install stow dotfiles package
  stow:
    state: present  # Note, 'latest' always register as changed
    package:
      - stow
      - git
    dir: "{{ ansible_env.HOME }}/dotfiles"
    target: "{{ ansible_env.HOME }}"
