- name: Install packages required by Emacs
  become: true
  ansible.builtin.apt:
    name:
      # Used for Emacs magit
      - git
      # Used for Emacs vterm
      - cmake
      - libtool-bin
      - libvterm-dev
      # Used by flyspell
      - hunspell
      - hunspell-en-us
      - hunspell-sv
      # Running screen inside vterm
      - screen
      # Used inside Emacs
      - fonts-firacode
      - ripgrep
      - texlive-latex-extra
    cache_valid_time: 3600
    state: present
    install_recommends: no

- name: Install Emacs via snap
  become: true
  community.general.snap:
    name: emacs
    classic: true

- name: Install dotfiles package used via Emacs
  stow:
    state: present
    package: "{{ item }}"
    dir: "{{ ansible_env.HOME }}/dotfiles"
    target: "{{ ansible_env.HOME }}"
  with_items:
    - screen
    - emacs
