- name: Install packages required by Emacs
  become: true
  ansible.builtin.apt:
    name:
      # Used for Emacs magit
      - git
      # Used for exporting org-mode
      - texlive-plain-generic
      # Used for Emacs vterm
      - cmake
      - libtool-bin
      - libvterm-dev
      # Used by flyspell
      - hunspell
      - hunspell-en-us
      - hunspell-sv
      # Running screen inside vterm
      - screen
      # Used inside Emacs
      - fonts-firacode
      - ripgrep
      - texlive-latex-extra
    cache_valid_time: 3600
    state: present
    install_recommends: no

- name: Install Emacs via snap
  become: true
  community.general.snap:
    name: emacs
    classic: true

- name: Install dotfiles package used via Emacs
  stow:
    state: present
    package: "{{ item }}"
    dir: "{{ ansible_env.HOME }}/dotfiles"
    target: "{{ ansible_env.HOME }}"
  with_items:
    - screen
    - emacs

- name: Install PlantUml used in org-mode Babel code blocks
  # Latest version is available from
  #   https://github.com/plantuml/plantuml
  # Current version is
  #   https://github.com/plantuml/plantuml/releases/download/v1.2024.8/plantuml-1.2024.8.jar
  vars:
    version: 1.2024.8
  block:
    - name: Ensure target directory exists
      ansible.builtin.file:
        path: ~/.local/plantuml
        state: directory
      loop:

    - name: "Download PlantUml jar file v{{ 1.2024.8 }}"
      ansible.builtin.get_url:
        url: "https://github.com/plantuml/plantuml/releases/download/v{{ version }}/plantuml-{{ version }}.jar"
        dest: "~/.local/plantuml/plantuml-{{ version }}.jar"

    - name: Create symbolic link to PlantUml jar file
      ansible.builtin.file:
        src: "~/.local/plantuml/plantuml-{{ version }}.jar"
        dest: ~/.local/plantuml/plantuml.jar
        state: link

- name: Install Graphviz used in PlantUml
  become: true
  ansible.builtin.apt:
    name:
      - graphviz
    cache_valid_time: 3600
    state: latest
    install_recommends: no
