- name: Install required packages for zsh
  become: true
  ansible.builtin.apt:
    name:
      - zsh
    cache_valid_time: 3600
    state: present
    install_recommends: no

- name: Install fzf
  block:
    - name: Download prebuilt binary
      ansible.builtin.get_url:
        url: https://github.com/junegunn/fzf/releases/download/v0.56.3/fzf-0.56.3-linux_amd64.tar.gz
        dest: /tmp/fzf-0.56.3-linux_amd64.tar.gz
        checksum: sha256:78e96a88cecfbdb3ff65df89cc47c02573407aee0edd08c87e18a8033d498fef

    - name: Unarchive the fzf binary
      ansible.builtin.unarchive:
        src: /tmp/fzf-0.56.3-linux_amd64.tar.gz
        dest: ~/.local/bin

# - name: Debug messages
#   debug:
#     # var: ansible_env
#     msg:
#       - Or write messages instead of var..
#       - "original user {{ target_user }}"
#       - "current user {{ ansible_env.USER }}"

# Install via downloading .sh file that has a known hash
# We have an installation instruction like
#   curl -sS https://starship.rs/install.sh | sh
#
# Find out md5 value on Windows with
#   CertUtil -hashfile yourFileName MD5
#
# MD5 hash of C:\Users\tim\Downloads\install.sh:
# 7a2db9f2d0e34bbee35d9b710ceb1a12
#
# starship --version
# starship 1.19.0
# branch:master
# commit_hash:
# build_time:2024-05-15 17:09:04 +00:00
# build_env:rustc 1.78.0 (9b00956e5 2024-04-29),
- name: Install the Starship prompt
  block:
    - name: Set expected md5 of starship installer
      set_fact:
        md5_value: 7a2db9f2d0e34bbee35d9b710ceb1a12

    - name: Download install file for starship and verify md5
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        checksum: "md5:{{ md5_value }}"
      register: download_install_file

    - name: Install starship using downloaded shell script
      become: true
      ansible.builtin.script:
        cmd: /tmp/starship_install.sh --yes
      when: download_install_file.changed

- name: "Ensure default shell is /bin/zsh for {{ ansible_env.USER }}"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- name: Install dotfiles packages used by zsh
  stow:
    state: present
    package:
      - zsh
      - starship
    dir: "{{ ansible_env.HOME }}/dotfiles"
    target: "{{ ansible_env.HOME }}"

